baseurl = "http://gscacco.github.io/"
languageCode = "it-it"
title = "G.Scacco"
canonifyurls = true
description = "Un blog di informatica e dintorni"
disqusShortname = "gscaccoio"
theme = "gscacco-hugo-redlounge"
[params]
author = "G.Scacco"
gaid = "UA-62774857-1"
sidebartitle = "gscaccoio"
sidebartagline = "Programmazione e dintorni"
[[menu.footer]]
name = "Blog"
url = "/post"
[[menu.social]]
pre = "<i class='fa fa-twitter'></i>"
url = "https://twitter.com/gscaccoio"
identifier = "twitter"
